server:
  port: 8092

### aliyun 邮件推送
email:
    host: smtpdm.aliyun.com
    port: 80
    username: support@yanxisir.com
    password: YanxiSir123
    from: support@yanxisir.com
    contact: support@yanxisir.com
    nick: support

spring:
   freemarker:
      enabled: true
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      settings:
        template_update_delay: 0
